language: bash
sudo: required

before_install:
  - docker pull weecology/portal_predictions
  - docker run --name ppred -t -d weecology/portal_predictions /bin/bash
  - docker cp ../portalPredictions ppred:/
  - docker exec -i ppred ls portalPredictions

script:
  - docker exec -e GITHUB_PAT=$GITHUB_PAT -i ppred bash -c "cd portalPredictions && Rscript test_1.R"
  - docker exec -e GITHUB_PAT="$GITHUB_PAT" -i ppred bash -c "cd portalPredictions && Rscript test_1.R"
