---
title: "Report - Latest Rodent Data"
---
Here's the most recent actual data (blue) compared to the forecast performed 
right before data collection (black, with error bars)
```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("tools/forecast_tools.R")

# get most recent rodent data
rodents <- portalr::abundance("repo", clean = FALSE, shape = "flat", 
                              level = "treatment", length = "longterm")
most_recent_period <- max(rodents$period)
observed <- dplyr::filter(rodents, period == most_recent_period, 
                          treatment == "control")

# get new moon number associated with this period
url_base <- "https://raw.githubusercontent.com/weecology/PortalData/master/"
url_suff <- "Rodents/moon_dates.csv"
url_full <- paste(url_base, url_suff, sep = "")
data_text <- RCurl::getURL(url_full)
newmoons_table <- read.csv(text = data_text)
newmoons_table$censusdate <- as.Date(newmoons_table$censusdate, 
                                     format = "%Y-%m-%d")
moon_code <- newmoons_table %>%
             dplyr::filter(period == most_recent_period) %>% 
             dplyr::select(newmoonnumber) %>% 
             as.integer()
most_recent_date <- newmoons_table %>%
                    dplyr::filter(period == most_recent_period) %>% 
                    dplyr::pull(censusdate)

# get most recent forecast prior to data collection
fnames <- list.files(path = "./predictions", pattern = "*forecasts.csv")
files <- data.frame(names = fnames)
files$filedates <- as.Date(substr(files$names, 1, 10),format = "%Y-%m-%d")
latest_forecast <- files %>%
                   dplyr::filter(filedates < most_recent_date) %>% 
                   tail(1)

fname <- paste("predictions/", latest_forecast$names, sep = "")
data <- read.csv(fname, na.strings = "")

ensemble <- data %>% 
            dplyr::filter(level == "Controls", model == "Ensemble", 
                          newmoonnumber == moon_code)
sp_predictions <- get_sp_predicts(ensemble, "Controls", lead_time = 1)


joined_data <- dplyr::left_join(sp_predictions, observed, by = "species")
joined_data[is.na(joined_data)] <- 0
which_tot <- joined_data$species == "total"
joined_data[which_tot, "abundance"] <- sum(joined_data$abundance, na.rm=T)
joined_data[which_tot, "period"] <- most_recent_period

plot_title <- paste0(sp_predictions$forecast_date[2], ": Control plots")
sp_predict <- plot_species_forecast(sp_predictions, title = plot_title)  
sp_predict = sp_predict + 
             ggplot2::geom_point(data = joined_data, 
               mapping = ggplot2::aes(x = abundance, y = species),
               color = "blue")
plot(sp_predict)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("tools/forecast_tools.R")

# get most recent rodent data
rodents <- portalr::abundance("repo", clean=FALSE, shape = "flat")
most_recent_period <- max(rodents$period)
observed <- dplyr::filter(rodents, period == most_recent_period)

# get new moon number associated with this period
url_base <- "https://raw.githubusercontent.com/weecology/PortalData/master/"
url_suff <- "Rodents/moon_dates.csv"
url_full <- paste(url_base, url_suff, sep = "")
data_text <- RCurl::getURL(url_full)
newmoons_table <- read.csv(text = data_text)
newmoons_table$censusdate <- as.Date(newmoons_table$censusdate,
                                     format = "%Y-%m-%d")
moon_code <- newmoons_table %>%
             dplyr::filter(period == most_recent_period) %>% 
             dplyr::select(newmoonnumber) %>% 
             as.integer()
most_recent_date <- newmoons_table %>%
                    dplyr::filter(period == most_recent_period) %>% 
                    dplyr::pull(censusdate)

# get most recent forecast prior to data collection
fnames <- list.files(path = "./predictions", pattern = "*forecasts.csv")
files <- data.frame(names = fnames)
files$filedates <- as.Date(substr(files$names, 1, 10), format = "%Y-%m-%d")
latest_forecast <- files %>%
                   dplyr::filter(filedates < most_recent_date) %>% 
                   tail(1)

fname <- paste("predictions/", latest_forecast$names, sep = "")
data <- read.csv(fname, na.strings = "")

ensemble <- dplyr::filter(data, level == "All", model == "Ensemble", 
              newmoonnumber == moon_code)
sp_predictions <- get_sp_predicts(ensemble, "All", lead_time = 1)


joined_data <- dplyr::left_join(sp_predictions, observed, by = "species")
joined_data[is.na(joined_data)] = 0
which_tot <- joined_data$species == "total"
joined_data[which_tot, "abundance"] <- sum(joined_data$abundance,na.rm=T)
joined_data[which_tot, "period"] <- most_recent_period

plot_title <- paste0(sp_predictions$forecast_date[2], ": All plots")
sp_predict <- plot_species_forecast(sp_predictions,title = plot_title)  
sp_predict <- sp_predict + 
              ggplot2::geom_point(data = joined_data, 
                mapping = ggplot2::aes(x = abundance, y = species),
                color = "blue")
plot(sp_predict)
```